import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { runPhaseC9RowReconciliation } from '../scripts/phase-c9-row-reconciliation.mjs';
import { createPhaseC9MockFetch } from './phase-c9-test-utils.mjs';

const out = path.join(os.tmpdir(), `c9-row-reconciliation-${Date.now()}.json`);
const fetchImpl = await createPhaseC9MockFetch();
const result = await runPhaseC9RowReconciliation({ outPath: out, fetchImpl });
assert.equal(result.summary.oddsDeploymentAllowed, false);
const data = JSON.parse(fs.readFileSync(out, 'utf8'));
assert.equal(data.summary.oddsDeploymentAllowed, false);
assert.ok(data.summary.endpoints.productionLive);
assert.ok(data.summary.rowCounts);
assert.ok(Array.isArray(data.eventsstat));
assert.ok(data.summary.eventsstatProbeMode);
assert.ok('marketSeriesCount' in data.eventsstat[0]);
assert.ok('scoreAlignmentSample' in data.eventsstat[0]);
assert.ok(data.eventsstat[0].marketSeriesCount > 0);
assert.ok(data.eventsstat[0].scoreAlignmentSample.length > 0);
console.log('Phase C9 row reconciliation smoke test passed');
