import fs from 'fs';
import assert from 'assert';
import path from 'path';
import { normalizeCalendarRow, normalizeCalendarPayload } from '../../src/ipbl/parseOfficialApi.js';

const fixtureDir = 'fixtures/ipbl/calendar-row';
const fixtureFile = fs.readdirSync(fixtureDir).find((f) => f.endsWith('-calendar-row.json'));
assert.ok(fixtureFile, 'calendar-row fixture file exists');
const row = JSON.parse(fs.readFileSync(path.join(fixtureDir, fixtureFile), 'utf8'));
const game = normalizeCalendarRow(row);
assert.strictEqual(game.gameId, 1069912);
assert.strictEqual(game.divisionTag, 'ipbl-66-w-pro-b');
assert.strictEqual(game.score1, 67);
assert.strictEqual(game.score2, 91);
assert.strictEqual(game.score, '67:91');
assert.strictEqual(game.fullScore, '19:31,20:24,16:17,12:19');
assert.strictEqual(game.date, '01.06.2026');
assert.strictEqual(game.team1, 'Cheboksary');
assert.strictEqual(game.team2, 'Tambov');
assert.throws(() => normalizeCalendarRow({ game: { id: 1 } }), /missing required score fields/);
const onlineRow = JSON.parse(fs.readFileSync(path.join(fixtureDir, 'game-1024850-calendar-online-row.json'), 'utf8'));
const onlineGame = normalizeCalendarRow(onlineRow);
assert.strictEqual(onlineGame.gameId, 1024850);
assert.strictEqual(onlineGame.divisionTag, 'ipbl-66-m-pro-c');
assert.strictEqual(onlineGame.score1, 87);
assert.strictEqual(onlineGame.score2, 76);
assert.strictEqual(onlineGame.score, '87:76');
assert.strictEqual(onlineGame.fullScore, null);
assert.strictEqual(onlineGame.date, '09.02.2026');
assert.strictEqual(onlineGame.team1, 'Voronezh');
assert.strictEqual(onlineGame.team2, 'Plavsk');
const payload = { data: { items: [row, onlineRow, { game: { showScore: false } }] } };
assert.strictEqual(normalizeCalendarPayload(payload).length, 2);
console.log(JSON.stringify({ ok: true, normalized: game, normalizedOnline: onlineGame }, null, 2));
